### ISSUE TITLE
 Glavni program, uvoz, grafi, poročilo

### ISSUE THREAD

**Issue by jaanos** [jlenarcic/APPR-2014-15#1]
V glavnem programu (`projekt.r`) kličeš vzorčna programa za naslednji dve fazi. Seveda ni smiselno, da ju sedaj kličeš, tako da ju zaenkrat zakomentiraj - v prihodnjih fazah boš seveda to vrnil (pa morda še kaj dodal).

Imena igralcev in ekip se ne ponavljajo, tako da jih lahko imaš za imena vrstic. Tako lahko podaš parameter `row.names = 1` pri uvažanju iz CSV. Namesto, da pridružuješ z `merge` (kar ti bo premešalo vrstice), raje enostavno naredi novo razpredelnico z `data.frame`:
```R
NBA <- data.frame(NBA1, OT)
```
Tako ne bo problemov z odvečnim prvim stolpcem in nepotrebnimi imeni. Mimogrede, pri spremenljivki z vrednostma da/ne ni ravno smiselno uvajati urejenosti.

Program naj ne izpisuje razpredelnic z `View` - to je sicer koristno, dokler delaš, a edini izhod naj bo graf (ali več njih) v datoteki PDF, ki ga boš vključil v poročilo.

Nikjer ne kličeš programa `Grafi.R` - to lahko narediš v glavnem programu (pazi na velikost črk!).

Ne pozabi vključiti grafov v poročilo. Seveda lahko vzorčna grafa pobrišeš.

**Comment by jlenarcic** [comment]
Kako bi ta dva zemljevida spravil na eno stran. Verjetno je treba zmanjšati velikost, vendar nimam ideje, kako bi to naredil.
\includepdf[pages={1-2}]{../slike/USAstats.pdf}

Lep pozdrav,
JL

**Comment by jaanos** [comment]
Če hočeš z `\includepdf` več grafov spraviti na eno stran, si pomagaš s parametrom `nup`, npr.
```LaTeX
\includepdf[pages={1-2},nup=1x2]{../slike/USAstats.pdf}
```
ti postavi en zemljevid nad drugega.

**Comment by jlenarcic** [comment]
Danes sem bil pri profesorju na zagovoru in že dobil oceno, le nekatere malenkosti sem še moral izboljšati. Sedaj pa sem popravil še zadnje stvari v poročilu , tako da imam sedaj zadnjo verzijo poročila.

Lep pozdrav

**Comment by jlenarcic** [comment]
Danes sem bil pri profesorju na zagovoru in že dobil oceno, le nekatere malenkosti sem še moral izboljšati. Sedaj pa sem popravil še zadnje stvari v poročilu , tako da imam sedaj zadnjo verzijo poročila.

Lep pozdrav
