### ISSUE TITLE
Zemljevid

### ISSUE THREAD

**Issue by jaanos** [jlenarcic/APPR-2014-15#4]
Pri prvem zemljevidu bi lahko izboljšal berljivost. Za začetek svetujem, da uporabiš kak drug zemljevid ZDA, npr. [tega](http://audrey.fmf.uni-lj.si/states_21basic.zip) - ta, ki ga uporabljaš, je namreč zelo velik in natančen (sam ZIP je velik kar 30MB). Tako bo tudi poročilo bolj gladko delovalo.

Da bo zemljevid lepo berljiv, svetujem, da uporabiš svetlejšo barvo mej držav - pri ukazu `plot` jo podaš s parametrom `border`. Tudi določanje barv bi se dalo lepše izvesti z indeksi namesto z `ifelse`. Tako bi lahko naredil:

``` R
barve.konference <- c("Atlantic" = "lightpink1",
                      "Central" = "lightskyblue2",
                      "Southeast" = "lightsteelblue4",
                      "Northwest" = "lightcyan3",
                      "Pacific" = "lightcoral",
                      "Southwest" = "lightgoldenrod")
plot(usa.states, col = barve.konference[usa4[as.character(usa.states$STATE_NAME),
                                   "conference"]], border = "grey")
```

Glede na to, da imaš za konferenco urejen faktor, imen za vektor `barve.konference` pravzaprav sploh ne bi potreboval (seveda morajo potem barve ustrezati urejenosti).

Ko vključuješ zemljevid v poročilo, navedi njegovo širino, da ne bo prevelik:

``` LaTeX
\makebox[\textwidth][c]{
\includegraphics[width=1.2\textwidth]{../slike/USAcities.pdf}
}
```

**Comment by jaanos** [comment]
Strežnik audrey.fmf.uni-lj.si je ugasnil, tako da predlagana povezava več ne deluje. Zemljevid je sedaj na voljo na naslovu http://baza.fmf.uni-lj.si/states_21basic.zip.

**Comment by jlenarcic** [comment]
V zadnji fazi sem narisal dendogram in ga poimenoval hierarhija1. Funkcija jemlje podatke iz tabele, kjer več pomeni boljše (podatki za skoke, asistence, točke, zmage,..). Imam občutek, da mi ekipe, ki bi morale biti med najslabšimi, vrže v drugo skupino, srednje dobre ekipe pa v zadnjo, tretjo skupino, kar se mi seveda zdi narobe? Mi lahko poveste, če gre kaj narobe? Kaj natančno dela funkcija scale? Na podlagi čega funkcija postavi ekipo v določeno skupino (1 pomeni največ/najboljše?)? Za odgovore se vam zahvaljujem.
Lep pozdrav

**Comment by jaanos** [comment]
Številka skupine ne pomeni določenega vrstnega reda - navsezadnje je
razvrščanje v skupine uporabno tudi takrat, ko ne iščemo neke linearne
urejenosti. Če torej dobiš tako razvrščanje, kot ga opisuješ, to napiši v
poročilu,

Funkcija scale od vsakega stolpca odšteje njegovo povprečje ter nato
dobljene vrednosti deli z njihovim standardnim odklonom. Tako dosežeš, da
lahko primerjaš prej neprimerljive vrednosti - seveda ob predpostavki, da
imajo vsi stolpci isto težo. Različne metode razvrščanja v skupine potem
razvrščajo glede na "razdaljo" med tako normiranimi vrsticami. Kot rečeno,
so številke tukaj le oznake in ne pomenijo vrstnega reda (pri metodi
voditeljev bi celo vsakič dobil različne številke skupin).

Dne 01. marec 2015 11.40 je jlenarcic <notifications@github.com> napisal/-a:
